apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  selector:
    app: phpmyadmin
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.120
  ports:
    - protocol: TCP
      name: https
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000