apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.120
  ports:
    - protocol: TCP
      name: https
      port: 10101
      targetPort: 10101
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: telegraf
        image: telegraf-image
        imagePullPolicy: Never
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock