apiVersion: v1
kind: Service
metadata:
  name: ftp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.120
  selector:
    app: ftp
  ports:
    - protocol: TCP
      name: port-ftps
      port: 21
      targetPort: 21
    - port: 20021
      name: port-passv
      protocol: TCP
      targetPort: 20021
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-deployment
  labels:
    app: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20021